# Logs
logs
*.log
npm-debug.log*

# Runtime data
pids
*.pid
*.seed

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules
jspm_packages

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history
.idea
.node_modules
node_modules
.vscode


#制定node镜像的版本
FROM node:8.9-alpine
#声明作者
MAINTAINER czy
# #移动当前目录下面的文件到app目录下
# ADD . /app/
# #进入到app目录下面，类似cd
# WORKDIR /app
#安装依赖
RUN npm install
#对外暴露的端口
EXPOSE 9000
#程序启动脚本
CMD ["npm", "start"]
